playerLoaded = 0
speedlimit = 420
lowSpeedLimit = 50
medSpeedLimit = 70
highSpeedLimit = 90
currentSpeed = 0
limitFlash = true
speedlimitValues = {["Joshua Rd"]=medSpeedLimit, 
					["East Joshua Road"]=medSpeedLimit, 
					["Marina Dr"]=lowSpeedLimit, 
					["Alhambra Dr"]=lowSpeedLimit, 
					["Niland Ave"]=lowSpeedLimit, 
					["Zancudo Ave"]=lowSpeedLimit, 
					["Armadillo Ave"]=lowSpeedLimit, 
					["Algonquin Blvd"]=lowSpeedLimit, 
					["Mountain View Dr"]=lowSpeedLimit, 
					["Cholla Springs Ave"]=lowSpeedLimit, 
					["Panorama Dr"]=lowSpeedLimit, 
					["Lesbos Ln"]=lowSpeedLimit, 
					["Calafia Rd"]=lowSpeedLimit, 
					["North Calafia Way"]=lowSpeedLimit, 
					["Cassidy Trail"]=lowSpeedLimit, 
					["Seaview Rd"]=lowSpeedLimit, 
					["Grapeseed Main St"]=lowSpeedLimit, 
					["Grapeseed Ave"]=lowSpeedLimit, 
					["Joad Ln"]=lowSpeedLimit, 
					["Union Rd"]=lowSpeedLimit, 
					["O'Neil Way"]=lowSpeedLimit, 
					["Senora Fwy"]=highSpeedLimit, 
					["Catfish View"]=lowSpeedLimit, 
					["Great Ocean Hwy"]=lowSpeedLimit, 
					["Paleto Blvd"]=lowSpeedLimit,
					["Duluoz Ave"]=lowSpeedLimit, 
					["Procopio Dr"]=lowSpeedLimit, 
					["Cascabel Ave"]=lowSpeedLimit, 
					["Procopio Promenade"]=lowSpeedLimit, 
					["Pyrite Ave"]=lowSpeedLimit, 
					["Fort Zancudo Approach Rd"]=lowSpeedLimit, 
					["Barbareno Rd"]=lowSpeedLimit, 
					["Ineseno Road"]=lowSpeedLimit, 
					["West Eclipse Blvd"]=lowSpeedLimit, 
					["Playa Vista"]=lowSpeedLimit, 
					["Bay City Ave"]=lowSpeedLimit, 
					["Del Perro Fwy"]=highSpeedLimit, 
					["Equality Way"]=lowSpeedLimit, 
					["Red Desert Ave"]=lowSpeedLimit, 
					["Magellan Ave"]=lowSpeedLimit, 
					["Sandcastle Way"]=lowSpeedLimit, 
					["Vespucci Blvd"]=lowSpeedLimit, 
					["Prosperity St"]=lowSpeedLimit, 
					["San Andreas Ave"]=lowSpeedLimit, 
					["North Rockford Dr"]=lowSpeedLimit, 
					["South Rockford Dr"]=lowSpeedLimit, 
					["Marathon Ave"]=lowSpeedLimit, 
					["Boulevard Del Perro"]=lowSpeedLimit, 
					["Cougar Ave"]=lowSpeedLimit, 
					["Liberty St"]=lowSpeedLimit, 
					["Bay City Incline"]=lowSpeedLimit, 
					["Conquistador St"]=lowSpeedLimit, 
					["Cortes St"]=lowSpeedLimit, 
					["Vitus St"]=lowSpeedLimit, 
					["Aguja St"]=lowSpeedLimit, 
					["Goma St"]=lowSpeedLimit, 
					["Melanoma St"]=lowSpeedLimit, 
					["Palomino Ave"]=lowSpeedLimit, 
					["Invention Ct"]=lowSpeedLimit, 
					["Imagination Ct"]=lowSpeedLimit, 
					["Rub St"]=lowSpeedLimit, 
					["Tug St"]=lowSpeedLimit, 
					["Ginger St"]=lowSpeedLimit, 
					["Lindsay Circus"]=lowSpeedLimit, 
					["Calais Ave"]=lowSpeedLimit, 
					["Adam's Apple Blvd"]=lowSpeedLimit, 
					["Alta St"]=lowSpeedLimit, 
					["Integrity Way"]=lowSpeedLimit,
					["Swiss St"]=lowSpeedLimit, 
					["Strawberry Ave"]=lowSpeedLimit,
					["Capital Blvd"]=lowSpeedLimit, 
					["Crusade Rd"]=lowSpeedLimit, 
					["Innocence Blvd"]=lowSpeedLimit,
					["Davis Ave"]=lowSpeedLimit,
					["Little Bighorn Ave"]=lowSpeedLimit,
					["Roy Lowenstein Blvd"]=lowSpeedLimit,
					["Jamestown St"]=lowSpeedLimit,
					["Carson Ave"]=lowSpeedLimit,
					["Grove St"]=lowSpeedLimit, 
					["Brouge Ave"]=lowSpeedLimit,
					["Covenant Ave"]=lowSpeedLimit, 
					["Dutch London St"]=lowSpeedLimit,
					["Signal St"]=lowSpeedLimit, 
					["Elysian Fields Fwy"]=highSpeedLimit,
					["Plaice Pl"]=lowSpeedLimit,
					["Chum St"]=lowSpeedLimit, 
					["Chupacabra St"]=lowSpeedLimit,
					["Miriam Turner Overpass"]=lowSpeedLimit,
					["Autopia Pkwy"]=lowSpeedLimit,
					["Exceptionalists Way"]=lowSpeedLimit,
					["La Puerta Fwy"]=highSpeedLimit,
					["New Empire Way"]=lowSpeedLimit,
					["Runway1"]="--",
					["Greenwich Pkwy"]=lowSpeedLimit,
					["Kortz Dr"]=lowSpeedLimit,
					["Banham Canyon Dr"]=lowSpeedLimit,
					["Buen Vino Rd"]=lowSpeedLimit, 
					["Route 68"]=highSpeedLimit, 
					["Zancudo Grande Valley"]=lowSpeedLimit,
					["Zancudo Barranca"]=lowSpeedLimit,
					["Galileo Rd"]=lowSpeedLimit,
					["Mt Vinewood Dr"]=lowSpeedLimit, 
					["Marlowe Dr"]=lowSpeedLimit,
					["Milton Rd"]=lowSpeedLimit,
					["Kimble Hill Dr"]=lowSpeedLimit,
					["Normandy Dr"]=lowSpeedLimit, 
					["Hillcrest Ave"]=lowSpeedLimit,
					["Hillcrest Ridge Access Rd"]=lowSpeedLimit,
					["North Sheldon Ave"]=lowSpeedLimit,
					["Lake Vinewood Dr"]=lowSpeedLimit,
					["Lake Vinewood Est"]=lowSpeedLimit,
					["Baytree Canyon Rd"]=lowSpeedLimit, 
					["Peaceful St"]=lowSpeedLimit, 
					["North Conker Ave"]=lowSpeedLimit,
					["Wild Oats Dr"]=lowSpeedLimit,
					["Whispymound Dr"]=lowSpeedLimit,
					["Didion Dr"]=lowSpeedLimit,
					["Cox Way"]=lowSpeedLimit, 
					["Picture Perfect Drive"]=lowSpeedLimit,
					["South Mo Milton Dr"]=lowSpeedLimit,
					["Cockingend Dr"]=lowSpeedLimit, 
					["Mad Wayne Thunder Dr"]=lowSpeedLimit,
					["Hangman Ave"]=lowSpeedLimit,
					["Dunstable Ln"]=lowSpeedLimit,
					["Dunstable Dr"]=lowSpeedLimit,
					["Greenwich Way"]=lowSpeedLimit,
					["Greenwich Pl"]=lowSpeedLimit,
					["Hardy Way"]=lowSpeedLimit,
					["Richman St"]=lowSpeedLimit,
					["Ace Jones Dr"]=lowSpeedLimit,
					["Los Santos Freeway"]=highSpeedLimit,
					["Senora Rd"]=lowSpeedLimit, 
					["Nowhere Rd"]=lowSpeedLimit,
					["Smoke Tree Rd"]=lowSpeedLimit, 
					["Cholla Rd"]=lowSpeedLimit, 
					["Cat-Claw Ave"]=lowSpeedLimit,
					["Senora Way"]=lowSpeedLimit, 
					["Palomino Fwy"]=highSpeedLimit,
					["Shank St"]=lowSpeedLimit, 
					["Macdonald St"]=lowSpeedLimit, 
					["Route 68 Approach"]=highSpeedLimit,
					["Vinewood Park Dr"]=lowSpeedLimit,
					["Vinewood Blvd"]=lowSpeedLimit,
					["Mirror Park Blvd"]=lowSpeedLimit,
					["Glory Way"]=lowSpeedLimit, 
					["Bridge St"]=lowSpeedLimit, 
					["West Mirror Drive"]=lowSpeedLimit, 
					["Nikola Ave"]=lowSpeedLimit, 
					["East Mirror Dr"]=lowSpeedLimit, 
					["Nikola Pl"]=lowSpeedLimit, 
					["Mirror Pl"]=lowSpeedLimit,
					["El Rancho Blvd"]=lowSpeedLimit,
					["Olympic Fwy"]=highSpeedLimit,
					["Fudge Ln"]=lowSpeedLimit,
					["Amarillo Vista"]=lowSpeedLimit, 
					["Labor Pl"]=lowSpeedLimit,
					["El Burro Blvd"]=lowSpeedLimit,
					["Sustancia Rd"]=lowSpeedLimit,
					["South Shambles St"]=lowSpeedLimit, 
					["Hanger Way"]=lowSpeedLimit,
					["Orchardville Ave"]=lowSpeedLimit, 
					["Popular St"]=lowSpeedLimit,
					["Buccaneer Way"]=lowSpeedLimit,
					["Abattoir Ave"]=lowSpeedLimit,
					["Voodoo Place"]=lowSpeedLimit,
					["Mutiny Rd"]=lowSpeedLimit,
					["South Arsenal St"]=lowSpeedLimit,
					["Forum Dr"]=lowSpeedLimit,
					["Morningwood Blvd"]=lowSpeedLimit,
					["Dorset Dr"]=lowSpeedLimit,
					["Caesars Place"]=lowSpeedLimit, 
					["Spanish Ave"]=lowSpeedLimit,
					["Portola Dr"]=lowSpeedLimit,
					["Edwood Way"]=lowSpeedLimit,
					["San Vitus Blvd"]=lowSpeedLimit, 
					["Eclipse Blvd"]=lowSpeedLimit,
					["Gentry Lane"]=lowSpeedLimit,
					["Las Lagunas Blvd"]=lowSpeedLimit,
					["Power St"]=lowSpeedLimit, 
					["Mt Haan Rd"]=lowSpeedLimit, 
					["Elgin Ave"]=lowSpeedLimit,
					["Hawick Ave"]=lowSpeedLimit,
					["Meteor St"]=lowSpeedLimit, 
					["Alta Pl"]=lowSpeedLimit,
					["Occupation Ave"]=lowSpeedLimit, 
					["Carcer Way"]=lowSpeedLimit, 
					["Eastbourne Way"]=lowSpeedLimit,
					["Rockford Dr"]=lowSpeedLimit, 
					["Abe Milton Pkwy"]=lowSpeedLimit, 
					["Laguna Pl"]=lowSpeedLimit,
					["Sinners Passage"]=lowSpeedLimit, 
					["Atlee St"]=lowSpeedLimit,
					["Sinner St"]=lowSpeedLimit, 
					["Supply St"]=lowSpeedLimit, 
					["Amarillo Way"]=lowSpeedLimit,
					["Tower Way"]=lowSpeedLimit,
					["Decker St"]=lowSpeedLimit,
					["Tackle St"]=lowSpeedLimit,
					["Low Power St"]=lowSpeedLimit,
					["Clinton Ave"]=lowSpeedLimit,
					["Fenwell Pl"]=lowSpeedLimit, 
					["Utopia Gardens"]=lowSpeedLimit,
					["Cavalry Blvd"]=lowSpeedLimit,
					["South Boulevard Del Perro"]=lowSpeedLimit,
					["Americano Way"]=lowSpeedLimit,
					["Sam Austin Dr"]=lowSpeedLimit,
					["East Galileo Ave"]=lowSpeedLimit,
					["Galileo Park"]=lowSpeedLimit, 
					["West Galileo Ave"]=lowSpeedLimit, 
					["Tongva Dr"]=lowSpeedLimit,
					["Zancudo Rd"]=lowSpeedLimit,
					["Movie Star Way"]=lowSpeedLimit,
					["Heritage Way"]=lowSpeedLimit,
					["Perth St"]=lowSpeedLimit,
					["Chianski Passage"]=lowSpeedLimit,
					["Lolita Ave"]=lowSpeedLimit, 
					["Meringue Ln"]=lowSpeedLimit, 
					["Strangeways Dr"]=lowSpeedLimit,
					["York St"]=lowSpeedLimit}

function getSpeed()
    return speedlimit
end
function getStreet()
    return street
end

Citizen.CreateThread(function()
    while not playerLoaded do
	Citizen.Wait(50)
	if PlayerPedId() == -1 then playerLoaded = 1 end
    end
    while playerLoaded do
        Citizen.Wait(500)
        local playerloc = GetEntityCoords(GetPlayerPed(-1))
        local streethash = GetStreetNameAtCoord(playerloc.x, playerloc.y, playerloc.z)
        street = GetStreetNameFromHashKey(streethash)
        if IsPedInAnyVehicle(GetPlayerPed(-1)) then
			currentSpeed = GetEntitySpeed(GetPlayerPed(-1)) * 2.236936
            speedlimit = speedlimitValues[street]
            SpeedGui()
        else
            speedlimit = 0
            closeGui()
            Citizen.Wait(500)
        end
    end
end)

function SpeedGui()
    SendNUIMessage(
        {
            action = "display",
            type = speedlimit,
			currentSpeed = currentSpeed,
			lowSpeedLimit = lowSpeedLimit,
			medSpeedLimit = medSpeedLimit,
			highSpeedLimit = highSpeedLimit,
			limitFlash = limitFlash
        }
    )
end

function closeGui()
    SendNUIMessage(
        {
            action = "hide"
        }
    )
end
